### ISSUE TITLE
distinguish between updates + patches

### ISSUE THREAD

**Issue by MylesBorins** [targos/update-v8#11]
`update-v8 major` will completely replace the directory, where `update-v8 minor`will only patch in the lastest changes

I think a different commit message for the two types of updates can be really useful when auditing the tree to ensure that patches haven't been lost in the update

thoughts?

**Comment by targos** [comment]
I agree. I have confused both kinds of updates myself in the past. Do you have a suggestion?

**Comment by MylesBorins** [comment]
make different commit messages

minor === patch
major === update

**Comment by targos** [comment]
released in v3.4.4
